session_name: nchat
global_options:
  remain-on-exit: true
  default-shell: /bin/sh
  default-command: /bin/sh
  status: off
windows:
  - window_name: nchat
    panes:
      - shell_command:
          - "nchat"
    focus: 0
