# Compatible Fuzzel configuration for older versions, with Cascadia Code Nerd Font and custom dark theme

[main]
width=30
lines=14
anchor=center
line-height=26
font=FiraMono Nerd Font Medium:size=10:CaskaydiaMono Nerd Font
prompt="> "
icon-theme=WhiteSur-grey-dark
fields=name,filename,generic,comment
layer=overlay

[colors]
background=#101013e6
selection=1e3a8aff
text=e5e7ebff
selection-text=e5e7ebff
match=a5b4fcff
selection-match=a5b4fcff
border=1e3a8aff
