general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1

    col.active_border = rgba(33ccffee)
    col.inactive_border = rgba(595959aa)

    resize_on_border = false
    layout = master        # Keeps main window large for games
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

# Disable blur for all layers
layerrule = blur, none

animations {
    enabled = false  # Disable all animations for performance
}

dwindle {
    pseudotile = false
    preserve_split = false
}

master {
    new_status = master
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    focus_on_activate = true
    animate_manual_resizes = false
    enable_swallow = false
}

