source = input.conf
source = window.conf
source = looknfeel.conf

exec-once = /usr/bin/kdeconnectd
exec-once = wl-paste --type text --watch cliphist store
exec-once = swww-daemon
exec-once =/home/nick/.local/bin/wall/wall.py
exec-once = uwsm app -- swayosd-server

misc {
    disable_hyprland_logo = true
    disable_splash_rendering  = true
    focus_on_activate = true
}

monitor =,1920x1080@144,auto,1

exec = gsettings set org.gnome.desktop.interface icon-theme "WhiteSur-grey-dark"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec = gsettings set org.cinnamon.desktop.default-applications.terminal exec 'alacritty'
exec = gsettings set org.cinnamon.desktop.default-applications.terminal exec-arg '-e'

ecosystem {
  no_update_news = true
}

xwayland {
  force_zero_scaling = true
}

env = GBM_BACKEND,nvidia-drm
env = LIBVA_DRIVER_NAME,nvidia
env = SDL_VIDEODRIVER,wayland
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __NV_PRIME_RENDER_OFFLOAD,1
env = __VK_LAYER_NV_optimus,NVIDIA_only
env = WLR_RENDERER_ALLOW_SOFTWARE,1
env = MOZ_DISABLE_RDD_SANDBOX,1
env = EGL_PLATFORM,wayland

cursor {
    no_hardware_cursors = true
}
