general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd =  hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display.
    inhibit_sleep = 3
}

listener {
    timeout = 300 # 5mins
    on-timeout = loginctl lock-session
}
listener {
    timeout = 360
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' # shutoff screen
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
listener {
    timeout = 1200 # 20 mins
    on-timeout = systemctl suspend || loginctl suspend
}
