input {
    kb_layout = us,ru
    kb_variant =
    kb_options = grp:alt_space_toggle
    numlock_by_default = true
    follow_mouse = 1
    sensitivity = .5


    touchpad {
        natural_scroll = false
    }
}
device {
    name = logitech-mx-master-3s
    sensitivity = -1
}
$mainMod = SUPER
$shiftMod = SUPER SHIFT
$terminal = uwsm app -- alacritty 
$browser = vivaldi --password-store=gnome-libsecret --ozone-platform=wayland --ozone-platform-hint=wayland --enable-features=UseOzonePlatform
$fileManager = nemo

# App Launch Bindings
bind = $mainMod, M, exec, uwsm stop
bindd = $mainMod, Return, Terminal, exec, $terminal
bindd = $mainMod, E, File Manager, exec, $fileManager
bindd = $mainMod, B, Browser, exec, $browser
bindd = $mainMod, T, Neovim, exec, $terminal -e nvim
bindd = $mainMod, R, App Launcher, exec, fuzzel
bind = $shiftMod, R, exec, killall -SIGUSR1 waybar

# Rotate window focus layout-wise
bindm = SHIFT, mouse:273, movewindow
bindm = SHIFT, mouse:272, resizewindow
binde = ALT,Tab,cyclenext
binde = ALT,Tab,bringactivetotop

# Windows
bind = $mainMod, G, togglefloating
bind = $mainMod, D, togglesplit
bind = $shiftMod, D, pseudo
bind = $mainMod, F, fullscreen
bind = SHIFT, ESCAPE, killactive

bind = $shiftMod, 1, workspace, 1
bind = $shiftMod, 2, workspace, 2
bind = $shiftMod, 3, workspace, 3
bind = $shiftMod, 4, workspace, 4
bind = $mainMod, 1, movetoworkspacesilent, 1
bind = $mainMod, 2, movetoworkspacesilent, 2
bind = $mainMod, 3, movetoworkspacesilent, 3
bind = $mainMod, 4, movetoworkspacesilent, 4

bind = $mainMod, Tab, workspace, m+1
bind = $mainMod SHIFT, Tab, workspace, m-1
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = $mainMod CTRL, down, workspace, empty

# Fn keys
bindle = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bindle = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPause, exec, playerctl pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous
bind = , XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
bind = , XF86Lock, exec, hyprlock
bindle = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume +5 --max-volume 100
bindle = , XF86AudioLowerVolume, exec, swayosd-client --output-volume -5 --max-volume 100
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = , Caps_Lock, exec, swayosd-client --caps-lock
bind = , Num_Lock, exec, swayosd-client --num-lock
bind = , Scroll_Lock, exec, swayosd-client --scroll-lock

# window=window output=screen region=region 
bind = $mainMod, PRINT, exec, hyprshot -m window
bind = , PRINT, exec, hyprshot -m output
bind = $shiftMod, PRINT, exec, hyprshot -m region
