layerrule {
  name = swaync-control-center
  match:class = swaync-control-center
  blur = on
  ignore_alpha = 0.5
}
layerrule {
  name = swaync-notification-window
  match:class = swaync-notification-window
  blur = on
  ignore_alpha = 0.5
}
layerrule {
  name = waybar
  match:class = waybar
  blur = on
  ignore_alpha = 0.5
}
layerrule {
  name = fuzzel
  match:class = fuzzel
  blur = on
  ignore_alpha = 0.5
}
windowrule {
  name = pavu
  match:class = (.*org.pulseaudio.pavucontrol.*)
  float = on
  size = 700 600
}
windowrule {
  name = imv
  match:class = imv
  float = on
  size = 1000 800
}
windowrule {
  name = qjournalctl
  match:class = qjournalctl
  float = on
  size = 1000 800
}
windowrule {
  name = nwg-clipman
  match:class = nwg-clipman
  float = on
  center = on
}
windowrule {
  name = simplecal
  match:class = ^(gsimplecal)$
  move = 1692 25
  float = on
}
windowrule {
  name = save
  match:title = ^(Authentication Required|Unlock Keyring|Login|qt-sudo)$
  float = on
  center = on
}
windowrule {
  name = save
  match:title = .*wants to save$
  float = on
  center = on
}
windowrule {
  name = xwayland
  match:xwayland = True
  no_blur = on
}
# nwg-look
# windowrule = float,class:(nwg-look)
# windowrule = size 700 600,class:(nwg-look)
# windowrule = move 10% 20%,class:(nwg-look)

# xdg-desktop-portal-gtk
# windowrule = float, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)
# windowrule = center, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)


### 🔒 Float & Center Authentication / Polkit Dialogs

### Opacity Overrides
windowrulev2 = match:class ^(mpv)$, opacity 1.0 override 1.0 override
windowrulev2 = match:title .*YouTube.*, opacity 1.0 override 1.0 override
windowrulev2 = match:title .*FlickyStream.*, opacity 1.0 override 1.0 override

### ⚙️ qt6ct (Qt6 Configuration Tool)
# windowrulev2 = float, class:^(qt6ct)$
# windowrulev2 = center, class:^(qt6ct)$

### 🔊 Audio Device Chooser / Panel
# windowrulev2 = float, title:^(Audio Devices|Sound Settings|Select Audio Device|Output Devices|Volume Control)$
# windowrulev2 = center, title:^(Audio Devices|Sound Settings|Select Audio Device|Volume Control)$


# General: float all qBittorrent windows
# windowrulev2 = float,class:deluge
# windowrulev2 = size 900 750,class:deluge
# windowrule = noblur, xwayland:1
