--ozone-platform=wayland
--ozone-platform-hint=wayland
--use-gl=desktop
--password-store=gnome-libsecret
--enable-accelerated-video-decode
--enable-accelerated-video-encode
--enable-features=VaapiVideoDecoder
--disable-features=UseChromeOSDirectVideoDecoder
--ignore-gpu-blocklist
--enable-zero-copy
