--ozone-platform=wayland
--ozone-platform-hint=auto
--enable-features=AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiOnNvidiaGPUs
--enable-parallel-downloading
--password-store=gnome-libsecret
