--ozone-platform=wayland
--ozone-platform-hint=auto
--enable-accelerated-video-decode
--enable-accelerated-video-encode
---enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoEncoder
--ignore-gpu-blocklist
--enable-zero-copy
--enable-parallel-downloading
--password-store=gnome-libsecret
