# KDE Connect Daemon (needs keyring)
exec-once = bash -c "sleep 2 && /usr/bin/kdeconnectd"

exec-once = gnome-keyring-daemon --start --components=secrets,gpg

# Clipboard history watcher (text/images)
exec-once = wl-paste --type text --watch cliphist store

# Launch swww daemon
exec-once = swww-daemon
exec-once =/home/nick/.local/bin/wall/wall.py

# App launchers via uwsm
exec-once = uwsm app -- swayosd-server
