# Monitor configuration
monitor =,1920x1080@144,auto,1

# Set  GNOME apps via gsettings
exec = gsettings set org.gnome.desktop.interface icon-theme "WhiteSur-grey-dark"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec = gsettings set org.cinnamon.desktop.default-applications.terminal exec 'alacritty'
exec = gsettings set org.cinnamon.desktop.default-applications.terminal exec-arg '-e'

# Don’t show update news on firstlaunch (Hyprland ecosystem)
ecosystem {
  no_update_news = true
}

# ----------------------------
# XWayland settings
# ----------------------------
xwayland {
  force_zero_scaling = true
}

