source = bindings.conf
source = looknfeel.conf
source = input.conf
source = window.conf

# Monitor configuration
monitor =,1920x1080@144,auto,1

# Set  GNOME apps via gsettings
exec = gsettings set org.gnome.desktop.interface icon-theme "WhiteSur-grey-dark"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec = gsettings set org.cinnamon.desktop.default-applications.terminal exec 'alacritty'
exec = gsettings set org.cinnamon.desktop.default-applications.terminal exec-arg '-e'
exec-once = bash -c "sleep 2 && /usr/bin/kdeconnectd"
exec-once = wl-paste --type text --watch cliphist store
exec-once = swww-daemon
exec-once =/bin/bash -c '/home/nick/.local/bin/wall/wall.py'
exec-once = uwsm app -- swayosd-server

ecosystem {
  no_update_news = true
}

# ----------------------------
# XWayland settings
# ----------------------------
xwayland {
  force_zero_scaling = true
}

