# ─────────────────────────────
# Window & General Settings
# ─────────────────────────────
term xterm-256color
scrollback_lines 10000
cursor_shape block
hide_window_decorations yes
enable_audio_bell no
copy_on_select yes
map super+c copy_to_clipboard
map super+v paste_from_clipboard
confirm_os_window_close 0

# ─────────────────────────────
# Colors
# ─────────────────────────────
foreground #d3dae3
background #101013
color0  #21222c
color1  #ff5555
color2  #50fa7b
color3  #f1fa8c
color4  #0072ff
color5  #ff79c6
color6  #8be9fd
color7  #bfbfbf
color8  #4d4d4d
color9  #ff6e6e
color10 #10b981
color11 #ffffa5
color12 #a5b4fc
color13 #ff92df
color14 #a4ffff
color15 #ffffff

# ─────────────────────────────
# Font
# ─────────────────────────────
font_family FiraMono Nerd Font
bold_font   FiraMono Nerd Font Bold
italic_font FiraMono Nerd Font Italic
bold_italic_font FiraMono Nerd Font Bold Italic
font_size 10

