# General Settings
scrollback_lines 10000
copy_on_select yes
confirm_os_window_close 0

# Cursor Settings
cursor_shape underline

# Font Settings
font_family FiraMono Nerd Font
font_size 11
bold_font                   auto
italic_font                 auto
bold_italic_font            auto

# Colors (Normal and Bright)
background #101013
foreground #F4F5F6
color0 #21222c
color1 #ff5555
color2 #00ff99
color3 #f1fa8c
color4 #0072ff
color5 #ff79c6
color6 #33ccff
color7 #bfbfbf
color8 #4d4d4d
color9 #ff6e6e
color10 #10b981
color11 #ffffa5
color12 #a5b4fc
color13 #ff92df
color14 #a4ffff
color15 #ffffff
