[text]
appendEmptyLine=true
autoBracket=false
autoReplace=false
autoSave=false
autoSaveInterval=1
darkBgColorValue=15
darkColorScheme=true
dateFormat=
dictionaryPath=
executeCommand=
executeScripts=false
font="FiraMono Nerd Font,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
inertialScrolling=false
lightBgColorValue=255
lineNumbers=false
maxSHSize=2
noIndent=false
noSyntaxHighlighting=false
noWrap=false
pastePaths=false
recentFiles=/home/nick/.config/hypr/input.conf, /etc/tmpfiles.d/mpd.conf, /etc/pam.d/passwd, /home/nick/.gnupg/gpg-agent.conf, /etc/pam.d/login, /etc/pam.d/ly, /etc/iwd/main.conf, /home/nick/Polka/local/bin/waybar/network.py, /etc/resolvconf.conf, /usr/local/bin/loggy.sh
recentFilesNumber=10
recentOpened=false
removeTrailingSpaces=false
saveLastFilesList=false
saveUnmodified=false
selectionHighlighting=false
showEndings=false
showWhiteSpace=false
skipNonText=true
spellCheckFromStart=false
textMargin=false
textTabSize=4
thickCursor=false
vLineDistance=-80

[window]
closeWithLastTab=false
disableMenubarAccel=false
fullscreen=false
hideSearchbar=false
hideSingleTab=false
max=true
menubarTitle=false
nativeDialog=true
noMenubar=false
noToolbar=true
openInWindows=false
position=none
prefSize=@Size(445 530)
sharedSearchHistory=false
showCursorPos=false
showLangSelector=false
showStatusbar=true
sidePaneMode=false
size=@Size(957 526)
splitterPos=150
startSize=@Size(700 500)
sysIcons=true
tabPosition=0
tabWrapAround=false
