[text]
appendEmptyLine=true
autoBracket=false
autoReplace=false
autoSave=false
autoSaveInterval=1
darkBgColorValue=15
darkColorScheme=true
dateFormat=
dictionaryPath=
executeCommand=
executeScripts=false
font="FiraMono Nerd Font,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
inertialScrolling=false
lightBgColorValue=255
lineNumbers=false
maxSHSize=2
noIndent=false
noSyntaxHighlighting=false
noWrap=false
pastePaths=false
recentFiles=/home/nick/Overload/boot/loader/loader.conf, /home/nick/Polka/config/wlogout/style.css, /home/nick/Polka/local/bin/logid/personal_logid.sh, /home/nick/Lit/docs/my_packages.txt, /home/nick/Lit/docs/nvim/lazyvim.json, /home/nick/Lit/docs/nvim/lazy-lock.json, /home/nick/Polka/config/nvim/init.lua, /home/nick/Lit/noah/archinstall/archinstall/scripts/__init__.py, /home/nick/Polka/noah/insidepy/etc_files.py, /home/nick/Lit/noah/archinstall/conf.json
recentFilesNumber=10
recentOpened=false
removeTrailingSpaces=false
saveLastFilesList=false
saveUnmodified=false
selectionHighlighting=false
showEndings=false
showWhiteSpace=false
skipNonText=true
spellCheckFromStart=false
textMargin=false
textTabSize=4
thickCursor=false
vLineDistance=-80

[window]
closeWithLastTab=false
disableMenubarAccel=false
fullscreen=false
hideSearchbar=false
hideSingleTab=false
max=true
menubarTitle=false
nativeDialog=true
noMenubar=false
noToolbar=false
openInWindows=false
position=none
prefSize=@Size(465 530)
sharedSearchHistory=false
showCursorPos=false
showLangSelector=false
showStatusbar=true
sidePaneMode=false
size=@Size(476 526)
splitterPos=150
startSize=@Size(700 500)
sysIcons=false
tabPosition=0
tabWrapAround=false
