// vim:set ts=4 sw=4 et:
tls cloudflare {
    remote-hostname "one.one.one.one";
};
options {
	pid-file "/run/named/named.pid";
    directory "/var/named";
    max-cache-size 200m;
    listen-on { 127.0.0.1; };
    allow-recursion {
    	127.0.0.1;
    };
    forward only;
    forwarders port 853 tls cloudflare {
        1.1.1.1;
        1.0.0.1;
    };
// if system time is wrong and can't connect
//    dnssec-validation no;
};
zone "localhost" IN {
    type master;
    file "localhost.zone";
};
zone "0.0.127.in-addr.arpa" IN {
    type master;
    file "127.0.0.zone";
};
