options {
    pid-file "/run/named/named.pid";
    directory "/var/named";
    max-cache-size 200m;

    listen-on port 53 { 127.0.0.1; };
    listen-on-v6 port 53 { ::1; };

    allow-recursion { 127.0.0.1; ::1; };

    forward only;

    // ONLY go through WireGuard DNS
    forwarders {
        10.2.0.1;   // WireGuard IPv4 DNS
    };

    dnssec-validation auto;
};
