options {
    pid-file "/run/named/named.pid";
    directory "/var/named";
    max-cache-size 200m;
    listen-on port 53 { 127.0.0.1; };
    allow-recursion { 127.0.0.1; };
    forward only;
    forwarders {
        10.2.0.1;
    };
};
zone "localhost" IN {
    type master;
    file "localhost.zone";
};
zone "0.0.127.in-addr.arpa" IN {
    type master;
    file "127.0.0.zone";
};
